import type { TypographyTheme } from "@/lib/types";
import { round } from "@/lib/typography/parse";
import { rem, quoteStack } from "./css-vars";

export function exportScss(theme: TypographyTheme): string {
  const lines: string[] = [];
  lines.push("// Generated by Onylogy Design Tools");
  lines.push("");
  lines.push(
    `$font-family-heading: ${quoteStack(theme.heading.family, theme.heading.fallback)};`,
  );
  lines.push(
    `$font-family-body: ${quoteStack(theme.body.family, theme.body.fallback)};`,
  );
  lines.push(`$font-base-size: ${rem(theme.basePx)};`);
  lines.push("");
  for (const step of theme.steps) {
    lines.push(`$font-${step.role}-size: ${step.fontSizeRem};`);
    lines.push(`$font-${step.role}-line-height: ${round(step.lineHeight, 3)};`);
    lines.push(`$font-${step.role}-weight: ${step.fontWeight};`);
    if (step.letterSpacingEm !== 0) {
      lines.push(
        `$font-${step.role}-letter-spacing: ${round(step.letterSpacingEm, 3)}em;`,
      );
    }
    lines.push("");
  }
  return lines.join("\n").trimEnd();
}
